### ISSUE TITLE
Advice for proper Awesome WM support

### ISSUE THREAD

**Issue by erniejunior** [linuxmint/mintdesktop#15]
Hi,

I think the possibility to easily change the window manager in XFCE and and MATE is really nice. Therefore I wanted to extend this functionality to the awesome window manager. I made a fork and fixed this (see [here](https://github.com/linuxmint/mintdesktop/compare/master...erniejunior:master) for the changes I made).

There are some things which I am not quite happy with yet. Therefore I wanted to ask for your advice before creating a pull request.
1. awesome does not support the `--replace` option like the other window managers do. Therefore I need to kill them all before starting a new one (see [this](https://github.com/linuxmint/mintdesktop/compare/master...erniejunior:master#diff-5011dd3114e9f7df4884f74f73d66d71R37) line). Maybe that could harm the other window managers? What do you think?
2. I decreased the sleep delay [here](https://github.com/linuxmint/mintdesktop/compare/master...erniejunior:master#diff-5011dd3114e9f7df4884f74f73d66d71R52) because otherwise switching between the window managers takes so long. I feel like there should be a smarter way to wait for all window managers to terminate. I tried `subprocess.call` instead of `Popen` but that one did not work.

I am looking forward to you advice!

**Comment by clefebvre** [comment]
This was merged (implemented by calexil) today.
