### ISSUE TITLE
XFCE has Super key issues

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintdesktop#21]
I believe the XFCE version of Linux Mint was trying to be like the Cinnamon version with a simple press of the Super (Start) key opening the menu. Unfortunately, this conflicts with any other keyboard shortcuts that use the Super key (for example, "xfce4-display-settings" uses Super+P out of the box). 

Compiz may introduce more complications.

[I developed a workaround](https://www.reddit.com/r/linuxmint/comments/6lrc3s/mint_xfce_edition_has_super_key_issues/) involving ksuperkey, but I don't think this will be beginner-friendly.

**Comment by clefebvre** [comment]
Not related to mintdesktop.
