### ISSUE TITLE
System lock-up with 'this session is locked' when inserting USB device when lockscreen is on

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintdesktop#23]
Mint 18.2 x64 XFCE edition.

When I insert a USB stick when the computer is locked, I get a messaging saying - mysteriously - that the 'session is locked'. On one of the two occasions on which this happened (only twice have I inserted a USB when the lockscreen was on), nothing would see to unlock the computer and I had to 'raise elephants'.

I imagine that this is the wrong place to post this bug, but I could not find anywhere better, I am afraid.

**Comment by clefebvre** [comment]
Not related to mintdesktop.

**Comment by CottonEaster** [comment]
> I imagine that this is the wrong place to post this bug, but I could not find anywhere better, I am afraid.

> Not related to mintdesktop.

@clefebvre, please advise where I should report this bug. Thank you.
