### ISSUE TITLE
XFCE: Mint-Y theme + root Thunar = unreadable banner

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintdesktop#24]
Please see the image below.

![image](https://user-images.githubusercontent.com/9998846/30253403-d64685ec-9673-11e7-9c49-b04ff4219779.png)

I wouldn't mention it, except that Thunar is the default file manager and Mint-Y is, obviously, a Mint theme. So this unreadable text is, in a sense, default behaviour.

EDIT: The XFCE-Dusk theme is similar to Mint-Y but produces a banner that is considerably - but still not perfectly - readable.

**Comment by clefebvre** [comment]
Not related to mintdesktop.
