### ISSUE TITLE
Courier 10 Pitch Tilde

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/mintdesktop#25]
Courier 10 Pitch style=Regular
/usr/share/fonts/X11/Type1/c0419bt_.pfb
Tilde '~' does not display correctly in applications
xed, tomboy, pretty much all apps in Mint

 CPU  AMD Athlon(tm) II P360 Dual-Core x 2
 MEM  3783MB (1009MB used)
SCSI  ATA WDC WD3200BEVT-7 320 GB
         TSSTcorp DVD+-RW TS-L633C
  OS  Linux Mint 18.2 Sonya
         Kernal Linux 4.10.0-33-generic x86_64
         MATE 1.18.0

**Comment by clefebvre** [comment]
Not related to mintdesktop.
