### ISSUE TITLE
Hibernate

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/mintdesktop#26]
Hibernate is messed up
I have yet to encounter an OS that Hibernates correctly
after Hibernate grub started showing boot menu
after several boots it went away

 CPU  AMD Athlon(tm) II P360 Dual-Core x 2
 MEM  3783MB (1009MB used)
SCSI  ATA WDC WD3200BEVT-7 320 GB
         TSSTcorp DVD+-RW TS-L633C
  OS  Linux Mint 18.2 Sonya
         Kernal Linux 4.10.0-33-generic x86_64
         MATE 1.18.0

**Comment by clefebvre** [comment]
Not related to mintdesktop.
