### ISSUE TITLE
Touchpad Indicator Is Blank

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/mintdesktop#27]
When switching the Touchpad ON/OFF the pop-up indicator is blank.

There is also NO Icon in the Notification Panel.

![touchpad indicator](https://user-images.githubusercontent.com/31071746/31090882-386f7b8e-a777-11e7-8ed6-04c91d4f632b.png)

**Comment by clefebvre** [comment]
Not related to mintdesktop.
