### ISSUE TITLE
Power Mananagement

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/mintdesktop#28]
Battery Low Shutdown -- does NOT!
Hibernates instead requiring HARD-SHUT-DOWN (hold power key until OFF)!
Linux Mint does NOT Hibernate correctly -- PERIOD!
Linux Mint does NOT manage power well, no battery settings for system, ie. processor.

#### MATE general version
MATE 1.18.0

#### Package version
unknown

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Additional Information
 CPU: AMD Athlon(tm) II P360 Dual-Core x 2
 MEM: 3783MB (1009MB used)
SCSI: ATA WDC WD3200BEVT-7 320 GB
      TSSTcorp DVD+-RW TS-L633C
DISP: Resolution 1366x768 pixels
      OpenGL Renderer Gallium 0.4
      AMD RS880 (DRM 2.49.0 / 4.10.0-32-generic,LLVM 4.0.0)

**Comment by clefebvre** [comment]
not related to mintdesktop.
