### ISSUE TITLE
WMF Preview Crashes ALL

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/mintdesktop#29]
This is a SYSTEM wide issue!
ALL Preview Capable Programs CRASH!
some Windows XP WMF's CRASH the application
no error message, application closes without notice

these WMF's come from WinXP TurboCAD
once edited & saved with Corel Draw the problem ends
preview needs to check for this error - missing drawing size
DO NOT VIEW WITH THUMBNAILS ENABLED - use 'List View'
	caja 1.18.3
	xviewer 1.4.3
	pix 1.4.5
#### MATE general version
MATE 1.18.0

#### Package version
unknown

#### Linux Distribution
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64

#### Additional Information
 CPU: AMD Athlon(tm) II P360 Dual-Core x 2
 MEM: 3783MB (1009MB used)
SCSI: ATA WDC WD3200BEVT-7 320 GB
      TSSTcorp DVD+-RW TS-L633C
DISP: Resolution 1366x768 pixels
      OpenGL Renderer Gallium 0.4
      AMD RS880 (DRM 2.49.0 / 4.10.0-32-generic,LLVM 4.0.0)

#### The Offending File
[WMF_Error.wmf.tar.gz](https://github.com/linuxmint/mintdesktop/files/1458166/WMF_Error.wmf.tar.gz)

**Comment by clefebvre** [comment]
not related to mintdesktop.
