### ISSUE TITLE
xfwm4+compton option is not saved after reboot

### ISSUE THREAD

**Issue by 91DarioDev** [linuxmint/mintdesktop#30]
i am using linux mint 18.3 32bit XFCE.

**PROBLEM**: xfwm4+compton option is not saved after reboot despite it says so.

**STEPS TO REPRODUCE:**
- install linux mint 18.3 32bit xfce
- change windows manager from default option to xfwm4+compton (using the gui)
- reboot

after the reboot, going in settings, windows manger, it says 'xfwm4+compton' but actually it's not used and it is used the default option (xfwm4).

i tried to search a bit online and i found also [this question having the same problem of mine](https://unix.stackexchange.com/questions/381043/make-linux-mint-choose-compton-by-default)

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintdesktop/commit/364fd51885821422ec9312de866a7a86381c4e13 should help with the original issue.

Upon reboot/login compton was started without the vsync/gl arguments.
