### ISSUE TITLE
Enabling fortune cookies

### ISSUE THREAD

**Issue by ThorodanBrom** [linuxmint/mintdesktop#34]
I noticed that in LM 19 XFCE, that the option to enable fortune cookies has been removed. I understand this is intentional, based on the most recent commits.
I just wanted to know if this ability has been shifted to some other settings manager. (To be honest, this was a weird place to put it from the beginning !)

**Comment by xenopeek** [comment]
No, it was removed not moved. You'd have to manually install the fortune-mod package with additionally one or more fortunes-* packages for providing the fortune messages (see dependencies on https://packages.ubuntu.com/bionic/fortune-mod for which fortunes-* packages there are). Then add the line `fortune` at the end of your ~/.bashrc file to have a fortune read to you every time you open a terminal.
