### ISSUE TITLE
Open-VM-Tools does not work properly in Mint 19 Xfce

### ISSUE THREAD

**Issue by Slapbox** [linuxmint/mintdesktop#35]
Sorry if this isn't the right place for this bug. I can't find anywhere that seems more correct.

I'm trying to use Mint 19 with VMWare Player, but I get all sorts of weirdness when I try. 18.3 worked great, however 19 has issues on both a fresh install and when upgrading from 18.3.

Here's a bug I opened at `open-vm-tools` which explains/demonstrates the issue: https://github.com/vmware/open-vm-tools/issues/271

**Comment by xenopeek** [comment]
I hope you were able to solve this issue already. If not, I'd suggest taking help to the forum to help with troubleshooting and finding root cause / responsible component. We have a virtualization section on the forum: https://forums.linuxmint.com/viewforum.php?f=231

**Comment by Slapbox** [comment]
Thanks for taking the time to clean up the issue tracker. For anyone who runs into this, what I did to resolve this was to change to xfce with software rendering at the login screen, rather than hardware rendering.
