### ISSUE TITLE
When using 'Switch User' window-manager-launcher terminates without starting a window manager

### ISSUE THREAD

**Issue by tuxlifan** [linuxmint/mintdesktop#7]
On Linux Mint 17.3 'Rosa', MATE Edition
Package: mintdesktop, Version: 3.4.3

* How to reproduce: Log in with one user, then choose Logout from the Menu and Switch User. Log in as a different user.

* Result: For the second user no window manager is started

* Expected: The second user should have a full DE including a window manager

* It happens always.

The problem seems to be that window-manager-launcher is trying to kill a process (e.g. marco) belonging to the first user; in line 36 ("os.kill(pid, signal.SIGKILL)")

A solution would be to modify the ps invocation in line 28 ("p = subprocess.Popen(['ps', '-A'], stdout=subprocess.PIPE)") in a way that limits ps output to processes belonging to the current user.

A quick&dirty workaround is to wrap the 'kill line' in a try-except block and catch and ignore the PermissionError (patch attached).

[trycatchPermissionError.txt](https://github.com/linuxmint/mintdesktop/files/72735/trycatchPermissionError.txt)

**Comment by yashengy** [comment]
Alternatively, one can kill only those processes belong to the current user. Patch attached.

[window-manager-launcher.diff.txt](https://github.com/linuxmint/mintdesktop/files/76132/window-manager-launcher.diff.txt)

**Comment by monsta** [comment]
@clefebvre: confirmed - see http://forums.linuxmint.com/viewtopic.php?f=206&t=212794

**Comment by clefebvre** [comment]
Funny bug that one :)

We'll get that fixed today. Thanks for the feedback.
